<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8881" started-at="2017-05-25T21:07:07Z" finished-at="2017-05-25T21:07:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8881" started-at="2017-05-25T21:07:07Z" finished-at="2017-05-25T21:07:16Z">
      <class name="moj.test.paket.LoginTest">
        <test-method status="PASS" signature="setupSelenium()[pri:0, instance:moj.test.paket.LoginTest@48eff760]" name="setupSelenium" is-config="true" duration-ms="8430" started-at="2017-05-25T21:07:07Z" finished-at="2017-05-25T21:07:16Z">
        </test-method> <!-- setupSelenium -->
        <test-method status="FAIL" signature="testLoginWrongUsername()[pri:0, instance:moj.test.paket.LoginTest@48eff760]" name="testLoginWrongUsername" duration-ms="173" started-at="2017-05-25T21:07:16Z" finished-at="2017-05-25T21:07:16Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at moj.paket.HomePage.getMessage(HomePage.java:28)
	at moj.test.paket.LoginTest.testLoginWrongUsername(LoginTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- testLoginWrongUsername -->
        <test-method status="PASS" signature="closeSelenium()[pri:0, instance:moj.test.paket.LoginTest@48eff760]" name="closeSelenium" is-config="true" duration-ms="184" started-at="2017-05-25T21:07:16Z" finished-at="2017-05-25T21:07:16Z">
        </test-method> <!-- closeSelenium -->
      </class> <!-- moj.test.paket.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
